#!/usr/bin/env python3
"""Regenerate Returner/Data.lua from Blizzard's official WoW news RSS feed.

Run locally:
    pip install feedparser
    python3 scripts/update_news.py

Or invoke from a GitHub Action (see .github/workflows/auto-update.yml).

Exits with status 0 if Data.lua was rewritten or already up to date.
Exits with status 2 if no items were fetched (used by CI to skip commit).
"""
from __future__ import annotations

import datetime as dt
import hashlib
import os
import re
import sys
from pathlib import Path

try:
    import feedparser  # type: ignore
except ImportError:
    sys.stderr.write("feedparser is required: pip install feedparser\n")
    sys.exit(1)

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

# Blizzard's official WoW news feed. Change here if the URL ever moves.
FEED_URL = "https://news.blizzard.com/en-us/world-of-warcraft.rss"

# Fallback feed in case Blizzard's is unreachable.
FALLBACK_FEED_URL = "https://www.wowhead.com/news/rss/all"

# How many items to keep in Data.lua. Older ones are dropped.
MAX_ITEMS = 40

# Minimum item age (in days) before we drop it.
MAX_AGE_DAYS = 365

ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = ROOT / "Data.lua"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

CATEGORY_KEYWORDS = [
    ("hotfix",  ["hotfix", "hotfixes"]),
    ("patch",   ["patch", "ptr", "release notes", "build", "update", "season"]),
    ("event",   ["event", "holiday", "darkmoon", "brewfest", "hallow", "noblegarden",
                 "love is in the air", "midsummer", "pilgrim", "winter veil",
                 "lunar festival", "trial of style", "children's week", "world boss"]),
    ("esports", ["arena world championship", "awc", "mdi", "mythic dungeon international",
                 "esports"]),
]

DEFAULT_CATEGORY = "news"


def categorize(title: str, summary: str) -> str:
    haystack = f"{title} {summary}".lower()
    for cat, keywords in CATEGORY_KEYWORDS:
        if any(kw in haystack for kw in keywords):
            return cat
    return DEFAULT_CATEGORY


def clean_html(text: str) -> str:
    """Strip HTML tags and collapse whitespace."""
    text = re.sub(r"<[^>]+>", " ", text or "")
    text = re.sub(r"&nbsp;", " ", text)
    text = re.sub(r"&amp;", "&", text)
    text = re.sub(r"&lt;", "<", text)
    text = re.sub(r"&gt;", ">", text)
    text = re.sub(r"&quot;", '"', text)
    text = re.sub(r"&#(\d+);", lambda m: chr(int(m.group(1))), text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def lua_escape(s: str) -> str:
    """Escape a Python string for safe inclusion inside Lua double-quoted string."""
    if not s:
        return ""
    s = s.replace("\\", "\\\\")
    s = s.replace('"', '\\"')
    s = s.replace("\n", " ")
    s = s.replace("\r", " ")
    return s


def fetch_feed(url: str):
    sys.stderr.write(f"Fetching {url}\n")
    feed = feedparser.parse(url)
    if feed.bozo and not feed.entries:
        sys.stderr.write(f"  bozo: {feed.bozo_exception}\n")
    return feed


def collect_entries():
    feeds = [FEED_URL, FALLBACK_FEED_URL]
    seen_titles = set()
    items = []
    cutoff = dt.datetime.now(dt.timezone.utc) - dt.timedelta(days=MAX_AGE_DAYS)

    for url in feeds:
        feed = fetch_feed(url)
        for entry in feed.entries:
            title = clean_html(getattr(entry, "title", "")).strip()
            if not title or title.lower() in seen_titles:
                continue
            seen_titles.add(title.lower())

            published = entry.get("published_parsed") or entry.get("updated_parsed")
            if not published:
                continue
            ts = dt.datetime(*published[:6], tzinfo=dt.timezone.utc)
            if ts < cutoff:
                continue

            summary = clean_html(getattr(entry, "summary", ""))[:400]
            link = getattr(entry, "link", "") or ""

            items.append({
                "timestamp": int(ts.timestamp()),
                "title": title,
                "body": summary,
                "url": link,
                "category": categorize(title, summary),
            })

        if len(items) >= MAX_ITEMS:
            break

    items.sort(key=lambda it: it["timestamp"], reverse=True)
    return items[:MAX_ITEMS]


def render_lua(items) -> str:
    now_iso = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    out = []
    out.append("-- Returner_Data is auto-generated by scripts/update_news.py.")
    out.append("-- Do NOT edit by hand. Regenerated daily by GitHub Actions from")
    out.append("-- Blizzard's official WoW news RSS feed.")
    out.append("")
    out.append("Returner_Data = {")
    out.append("    metadata = {")
    out.append(f'        generated_at = "{now_iso}",')
    out.append(f'        source       = "Blizzard WoW News RSS",')
    out.append(f"        count        = {len(items)},")
    out.append("    },")
    out.append("    items = {")
    for it in items:
        out.append("        {")
        out.append(f"            timestamp = {it['timestamp']},")
        out.append(f'            title     = "{lua_escape(it["title"])}",')
        out.append(f'            body      = "{lua_escape(it["body"])}",')
        out.append(f'            url       = "{lua_escape(it["url"])}",')
        out.append(f'            category  = "{it["category"]}",')
        out.append("        },")
    out.append("    },")
    out.append("}")
    out.append("")
    return "\n".join(out)


def hash_content(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


# Exclude metadata.generated_at from change detection so cron-only runs without
# real news changes don't churn commits.
GENERATED_AT_RE = re.compile(r'generated_at = "[^"]*"')


def stable_hash(text: str) -> str:
    return hash_content(GENERATED_AT_RE.sub('generated_at = ""', text))


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    items = collect_entries()
    if not items:
        sys.stderr.write("No items fetched. Aborting without rewriting Data.lua.\n")
        return 2

    new_content = render_lua(items)

    old_content = OUT_PATH.read_text(encoding="utf-8") if OUT_PATH.exists() else ""
    if stable_hash(old_content) == stable_hash(new_content):
        sys.stderr.write(f"Data.lua unchanged ({len(items)} items). Skipping write.\n")
        # Still write so generated_at gets refreshed, but signal "no real change" to CI
        # via a separate marker file the workflow can read.
        OUT_PATH.write_text(new_content, encoding="utf-8")
        Path(ROOT / ".update_marker").write_text("nochange", encoding="utf-8")
        return 0

    OUT_PATH.write_text(new_content, encoding="utf-8")
    Path(ROOT / ".update_marker").write_text("changed", encoding="utf-8")
    sys.stderr.write(f"Wrote {OUT_PATH} with {len(items)} items.\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
