name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run packager and upload to CurseForge
        uses: BigWigsMods/packager@master
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          # Optional, set if you also want to publish to Wago and/or WoWInterface:
          # WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          # WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
        with:
          args: -t  # -t = include topic-level changelog from CHANGELOG.md
